#:schema node_modules/wrangler/config-schema.json
name = "durable-object-starter"
main = "src/index.ts"
compatibility_date = "2024-10-22"

# Bind a Durable Object. Durable objects are a scale-to-zero compute primitive based on the actor model.
# Durable Objects can live for as long as needed. Use these when you need a long-running "server", such as in realtime apps.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#durable-objects
[[durable_objects.bindings]]
name = "MY_DURABLE_OBJECT"
class_name = "MyDurableObject"

# Durable Object migrations.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#migrations
[[migrations]]
tag = "v1"
new_classes = ["MyDurableObject"]

[vars]
AUTH_TOKEN = "YELLOW_BEAR_SUN"